19/09/2019 07:52:57 PM Python Script is: morePVs.py
19/09/2019 07:52:57 PM study_name = test_en_mk2
19/09/2019 07:52:57 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_6\studies\tests\outputs\test_en_mk2\saved_tariffs\static_import_tariffs.csv
19/09/2019 07:52:57 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_6\studies\tests\outputs\test_en_mk2\saved_tariffs\static_solar_import_tariffs.csv
19/09/2019 07:52:57 PM saved to C:\Users\z5044992\Documents\python\morePVs\DATA_EN_6\studies\tests\outputs\test_en_mk2\saved_tariffs\static_export_tariffs.csv
19/09/2019 07:52:57 PM Running Scenario number 0 
19/09/2019 07:52:57 PM 


 Exception !!!!!!
Traceback (most recent call last):
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 2633, in main
    runScenario(s)
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 2600, in runScenario
    scenario.calcFinancials(eno)
  File "C:/Users/z5044992/Documents/python/morePVs/morePVs.py", line 2153, in calcFinancials
    + self.total_battery_capex_repayment)*100 - net.total_building_payment
AttributeError: 'Scenario' object has no attribute 'pv_capex_repayment'
